### ISSUE TITLE
Include golang v1.17 as part of the integration tests in CCI

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/enigma-go#208]
With a released v1.17 of golang we should include it in the Circle CI testing pipeline. The current way of testing different versions in the `config.yml` can also probably simplified using the build matrix support, which would make it easier to add future versions as well.

```
workflows:
  build:
    jobs:
      - build:
          matrix:
            parameters:
              go_version:
                - "1.14"
                - "1.15"
                - "1.16"
                - "1.17"
```
